version: "2"
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  rabbitmq:
    image: rabbitmq
  bridge:
    build:
      context: ..
      dockerfile: ./dockerfiles/bridge-develop.dockerfile
    ports:
      - '6382:6382'
    working_dir: '/bridge'
    command: /usr/bin/env npm run start-dev
    environment:
      NODE_ENV: 'develop'
    volumes:
      - ../bridge/bin:/bridge/bin
      - ../bridge/lib:/bridge/lib
      - ../../core:/core
    links:
      - mongo
      - rabbitmq
  billing:
    build:
      context: ..
      dockerfile: ./dockerfiles/billing-develop.dockerfile
    ports:
      - '3000:3000'
    working_dir: '/billing'
    command: /usr/bin/env npm run start-dev
    environment:
      NODE_ENV: 'develop'
    volumes:
      - ../billing/bin:/billing/bin
      - ../billing/lib:/billing/lib
      - ../../service-storage-models:/service-storage-models
      - ../../core:/core
    links:
      - mongo
      - rabbitmq
