---
- name: Link storj node modules
  file:
    src: '~/{{ item[0] }}'
    path: '~/bridge-gui/node_modules/{{ item[1] }}'
    state: link
    force: yes
  with_nested:
   - "{{ modules }}"
   - "{{ modules }}"

